(.venv) PS C:\Users\hpnel\Downloads\test_app_sport\sport\backend> uvicorn app.main:app --reload
>>
INFO:     Will watch for changes in these directories: ['C:\\Users\\hpnel\\Downloads\\test_app_sport\\sport\\backend']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [54480] using WatchFiles
INFO:     Started server process [54048]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:55002 - "GET /api/dashboard HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 38, in read_dashboard
    return crud.get_dashboard_summary(session)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 125, in get_dashboard_summary
    todays_workouts = [_build_workout(session, all_templates[0])] if all_templates else []
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 37, in _build_workout
    exercise=schemas.ExerciseOut.from_orm(exercise),
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:55227 - "GET /api/workouts HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 43, in read_workouts
    return crud.list_workouts(session)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 66, in list_workouts
    return [_build_workout(session, template) for template in templates]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 66, in <listcomp>
    return [_build_workout(session, template) for template in templates]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 37, in _build_workout
    exercise=schemas.ExerciseOut.from_orm(exercise),
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:53300 - "GET /api/exercises HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 75, in read_exercises
    return [schemas.ExerciseOut.from_orm(ex) for ex in exercises]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 75, in <listcomp>
    return [schemas.ExerciseOut.from_orm(ex) for ex in exercises]
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:53301 - "GET /api/dashboard HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 38, in read_dashboard
    return crud.get_dashboard_summary(session)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 125, in get_dashboard_summary
    todays_workouts = [_build_workout(session, all_templates[0])] if all_templates else []
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 37, in _build_workout
    exercise=schemas.ExerciseOut.from_orm(exercise),
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:53303 - "GET /api/workouts HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 43, in read_workouts
    return crud.list_workouts(session)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 66, in list_workouts
    return [_build_workout(session, template) for template in templates]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 66, in <listcomp>
    return [_build_workout(session, template) for template in templates]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 37, in _build_workout
    exercise=schemas.ExerciseOut.from_orm(exercise),
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:53299 - "GET /api/calendar?month=10&year=2025 HTTP/1.1" 200 OK
INFO:     127.0.0.1:55201 - "GET /api/exercises HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 75, in read_exercises
    return [schemas.ExerciseOut.from_orm(ex) for ex in exercises]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 75, in <listcomp>
    return [schemas.ExerciseOut.from_orm(ex) for ex in exercises]
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:54943 - "GET /api/calendar?month=10&year=2025 HTTP/1.1" 200 OK
